from django.urls import path

from assignment_handler.views import (
    index,
    WorkerDetailView,
    WorkerCreateView,
    WorkerUpdateView,
    WorkerDeleteView,
    WorkersListView,
    TeamDetailView,
    TeamCreateView,
    TeamUpdateView,
    TeamDeleteView,
    PositionListView,
    PositionCreateView,
    PositionUpdateView,
    PositionDeleteView,
    TaskDetailView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TaskTypeListView,
    TaskTypeCreateView,
    TaskTypeUpdateView,
    TaskTypeDeleteView,
    ProjectDetailView,
    ProjectCreateView,
    ProjectUpdateView,
    ProjectDeleteView,
    ProjectCategoryListView,
    ProjectCategoryCreateView,
    ProjectCategoryUpdateView,
    ProjectCategoryDeleteView,
    DashboardView,
    TaskPanelView,
    ProjectTrackingPanelView,
    ToggleAssignTaskView,
    ToggleTeamTransitionView,
    SwitchTeamView,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "workers/<int:pk>/",
        WorkerDetailView.as_view(),
        name="worker-detail",
    ),
    path(
        "accounts/register/",
        WorkerCreateView.as_view(),
        name="worker-create",
    ),
    path(
        "workers/<int:pk>/update/",
        WorkerUpdateView.as_view(),
        name="worker-update",
    ),
    path(
        "workers/<int:pk>/delete/",
        WorkerDeleteView.as_view(),
        name="worker-delete",
    ),
    path(
        "workers_list/",
        WorkersListView.as_view(),
        name="workers-list",
        ),
    path(
        "positions/",
        PositionListView.as_view(),
        name="position-list",
    ),
    path(
        "positions/create/",
        PositionCreateView.as_view(),
        name="position-create",
    ),
    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update",
    ),
    path(
        "positions/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete",
    ),
    path(
        "teams/<pk>/",
        TeamDetailView.as_view(),
        name="team-detail",
    ),
    path(
        "teams/create/",
        TeamCreateView.as_view(),
        name="team-create",
    ),
    path(
        "teams/<int:pk>/update/",
        TeamUpdateView.as_view(),
        name="team-update",
    ),
    path(
        "teams/<int:pk>/delete/",
        TeamDeleteView.as_view(),
        name="team-delete",
    ),
    path(
        "tasks/<int:pk>/",
        TaskDetailView.as_view(),
        name="task-detail",
    ),
    path(
        "tasks/create/",
        TaskCreateView.as_view(),
        name="task-create",
    ),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete",
    ),
    path(
        "task-types/",
        TaskTypeListView.as_view(),
        name="task-type-list",
    ),
    path(
        "task-types/create/",
        TaskTypeCreateView.as_view(),
        name="task-type-create",
    ),
    path(
        "task-types/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task-type-update",
    ),
    path(
        "task-types/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete",
    ),
    path(
        "projects/<int:pk>/",
        ProjectDetailView.as_view(),
        name="project-detail",
    ),
    path(
        "projects/create/",
        ProjectCreateView.as_view(),
        name="project-create",
    ),
    path(
        "projects/<int:pk>/update/",
        ProjectUpdateView.as_view(),
        name="project-update",
    ),
    path(
        "projects/<int:pk>/delete/",
        ProjectDeleteView.as_view(),
        name="project-delete",
    ),
    path(
        "project-categories/",
        ProjectCategoryListView.as_view(),
        name="project-category-list",
    ),
    path(
        "project-categories/create/",
        ProjectCategoryCreateView.as_view(),
        name="project-category-create",
    ),
    path(
        "project-categories/<int:pk>/update/",
        ProjectCategoryUpdateView.as_view(),
        name="project-category-update",
    ),
    path(
        "project-categories/<int:pk>/delete/",
        ProjectCategoryDeleteView.as_view(),
        name="project-category-delete",
    ),
    path(
        "dashboard/",
        DashboardView.as_view(),
        name="dashboard",
    ),
    path(
        "task_panel/",
        TaskPanelView.as_view(),
        name="task-panel",
    ),
    path(
        "project_tracking_panel/",
        ProjectTrackingPanelView.as_view(),
        name="project-tracking-panel",
    ),
    path(
        "tasks/<int:pk>/toggle-assign/",
        ToggleAssignTaskView.as_view(),
        name="toggle-task-assign",
    ),
    path(
        "teams/<int:pk>/toggle-add/<int:team_id>/",
        ToggleTeamTransitionView.as_view(),
        name="toggle-team-transition",
    ),
    path(
        "teams/<int:pk>/switch/<str:action>/",
        SwitchTeamView.as_view(),
        name="switch-team",
    ),
]

app_name = "assignment_handler"
